USE Lab_1
GO
CREATE TABLE NATIONALTY(	
 ID INTEGER PRIMARY KEY IDENTITY(1,1),
 NATIONALITY_NAME VARCHAR(50) NOT NULL,
 CHECK(LEN(NATIONALITY_NAME) > 3)
);
GO

INSERT INTO NATIONALTY (NATIONALITY_NAME) VALUES('ABCD');
GO

insert into NATIONALTY(NATIONALITY_NAME) values('Sdad');

CREATE TRIGGER NATIONALITY_TRIGGER_UPDATE
ON NATIONALTY
AFTER UPDATE
AS
INSERT INTO ACTIONS_LOG (TABLE_NAME, ACTION_NAME) VALUES('Nationality', 'UPDATE');
GO

CREATE TRIGGER NATIONALITY_TRIGGER_INSERT
ON NATIONALTY
AFTER INSERT
AS
INSERT INTO ACTIONS_LOG (TABLE_NAME, ACTION_NAME) VALUES('Nationality', 'INSERT');
GO

CREATE TRIGGER NATIONALITY_TRIGGER_DELETE
ON NATIONALTY
AFTER DELETE
AS
INSERT INTO ACTIONS_LOG (TABLE_NAME, ACTION_NAME) VALUES('Nationality', 'DELETE');
GO

CREATE VIEW VW_NATIONALTY
AS
SELECT ID, NATIONALITY_NAME
FROM NATIONALTY;
GO

CREATE PROCEDURE INSERT_NATIONALTY 
    @NATIONALITY_NAME VARCHAR(50) 
WITH RECOMPILE    
AS  
    BEGIN TRY
       INSERT INTO NATIONALTY (NATIONALITY_NAME) VALUES(@NATIONALITY_NAME)
    END TRY
	BEGIN CATCH
	   SELECT ERROR_MESSAGE() AS ERROR_MESSAGE;
	END CATCH 
GO

CREATE PROCEDURE UPDATE_NATIONALTY 
    @ID INTEGER,
    @NATIONALITY_NAME VARCHAR(50) 
WITH RECOMPILE    
AS  
    BEGIN TRY
       UPDATE NATIONALTY SET NATIONALITY_NAME = @NATIONALITY_NAME WHERE ID = @ID
    END TRY
	BEGIN CATCH
	   SELECT ERROR_MESSAGE() AS ERROR_MESSAGE;
	END CATCH
GO

CREATE PROCEDURE SELECT_NATIONALTY 
WITH RECOMPILE    
AS  
    BEGIN TRY
       SELECT * FROM VW_NATIONALTY;
	   RETURN;
    END TRY
	BEGIN CATCH
	   SELECT ERROR_MESSAGE() AS ERROR_MESSAGE;
	END CATCH
GO


CREATE PROCEDURE DELETE_NATIONALTY 
    @ID INTEGER
WITH RECOMPILE    
AS  
    BEGIN TRY
       DELETE NATIONALTY WHERE ID = @ID
    END TRY
	BEGIN CATCH
	   SELECT ERROR_MESSAGE() AS ERROR_MESSAGE;
	END CATCH
GO   